title: Sharpsteen.net
description: |
  Charlie Sharpsteen blogs here once in a blue moon.
url: http://sharpsteen.net

author:
  name: Charlie Sharpsteen
  url: http://sharpsteen.net

github:
  repo: https://github.com/Sharpie

exclude:
  - 'Gemfile*'

permalink: /:categories/:title/

plugins:
  - jekyll-paginate

paginate: 5
