# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Sharpsteen.net
tagline: 
description: |
  Charlie Sharpsteen blogs here once in a blue moon.
url:              http://sharpsteen.net
paginate:         5

author:
  name:          'Charlie Sharpsteen'
  url:           http://sharpsteen.net

github:
  repo:           https://github.com/Sharpie
